"""Run All Migrations

Revision ID: 733ffceee29b
Revises:
Create Date: 2021-02-24 15:44:11.304498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '733ffceee29b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('phoneNumber', sa.String(
                        length=20), nullable=True),
                    sa.Column('username', sa.String(
                        length=30), nullable=False),
                    sa.Column('biography', sa.String(
                        length=200), nullable=True),
                    sa.Column('profilePicture', sa.String(
                        length=255), nullable=True),
                    sa.Column('hashed_password', sa.String(
                        length=255), nullable=False),
                    sa.Column('date_created', sa.DateTime(), nullable=True),
                    sa.Column('date_modified', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('name'),
                    sa.UniqueConstraint('username')
                    )
    op.create_table('follows',
                    sa.Column('follower_id', sa.Integer(), nullable=True),
                    sa.Column('followed_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], )
                    )
    op.create_table('posts',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('description', sa.String(
                        length=2000), nullable=True),
                    sa.Column('private', sa.Boolean(), nullable=False),
                    sa.Column('imagePath', sa.String(
                        length=255), nullable=True),
                    sa.Column('userId', sa.Integer(), nullable=False),
                    sa.Column('date_created', sa.DateTime(), nullable=True),
                    sa.Column('date_modified', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('comments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('userId', sa.Integer(), nullable=False),
                    sa.Column('postId', sa.Integer(), nullable=False),
                    sa.Column('content', sa.String(
                        length=255), nullable=False),
                    sa.Column('date_created', sa.DateTime(), nullable=True),
                    sa.Column('date_modified', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['postId'], ['posts.id'], ),
                    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('postLikes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('userId', sa.Integer(), nullable=False),
                    sa.Column('postId', sa.Integer(), nullable=False),
                    sa.Column('date_created', sa.DateTime(), nullable=True),
                    sa.Column('date_modified', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['postId'], ['posts.id'], ),
                    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('commentLikes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('userId', sa.Integer(), nullable=False),
                    sa.Column('commentId', sa.Integer(), nullable=False),
                    sa.Column('date_created', sa.DateTime(), nullable=True),
                    sa.Column('date_modified', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['commentId'], ['comments.id'], ),
                    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("commentLikes")
    op.drop_table("postLikes")
    op.drop_table('comments')
    op.drop_table('posts')
    op.drop_table('follows')
    op.drop_table('users')
    # ### end Alembic commands ###
